# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34acc83548f74c9c0fe5b2843f6ae96ddc4bc851346b394f7546589b788d486c1f5186ae5ca8a72ec3bfcc5e056bc886dea646f665b127ccf1cacf8981ad2fb3

test:
  secret_key_base: 61ec7c3c917a702355151fbae2790e1fce30eddaca077464ada694e23126fbf0499bf1b7f2c27f205439e30e69bd199a7604353800d06c9aa91036ae7d2114ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
